#!/usr/bin/env bash

"""
04_count_featurecounts.sh

Purpose:
  Quantify gene expression by counting how many reads map to each gene,
  using featureCounts on the aligned BAM files generated by STAR.

Inputs:
  - BAM files:
      $BAM_DIR/*.bam
      These are produced by 02_align_star.sh.

  - Gene annotation file (GTF):
      Automatically detected from:
      $GENOME_DIR/*.gtf

  - Configuration:
      workflow/00_config.sh
      Provides directory paths and THREADS.

Outputs:
  - Gene count matrix:
      $COUNT_DIR/gene_counts.txt

      This file contains:
        - Rows   → genes
        - Columns → samples
        - Values → number of read pairs assigned to each gene

  - Log file:
      $LOG_DIR/04_count_featurecounts.log


How to run:
  From the workflow directory:

      bash workflow/04_count_featurecounts.sh

  or from anywhere:

      bash path/to/workflow/04_count_featurecounts.sh


Notes:
  - This script counts paired-end reads (-p, --countReadPairs).
  - Uses the largest overlap rule for assigning reads to genes.
  - Automatically detects all BAM files in $BAM_DIR.
  - Requires featureCounts to be installed (Subread package).
  - Safe to re-run; output file will be overwritten.
"""

set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/00_config.sh"
ensure_dirs
validate_core_inputs

need_dir "$BAM_DIR"
gtf="$(ls -1 "$GENOME_DIR"/*.gtf | head -n1)"
need_file "$gtf"

LOG="$LOG_DIR/04_count_featurecounts.log"
echo "Logging to: $LOG"

{
  echo "Using annotation: $gtf"
  echo "BAM_DIR=$BAM_DIR"
  echo "THREADS=$THREADS"
  echo

  mapfile -t BAMS < <(find "$BAM_DIR" -maxdepth 1 -type f -name "*.bam" | sort)
  [[ "${#BAMS[@]}" -gt 0 ]] || { echo "ERROR: no BAMs found in $BAM_DIR"; exit 1; }

  out="$COUNT_DIR/gene_counts.txt"

  echo "BAM files found: ${#BAMS[@]}"
  echo "Running featureCounts -> $out"

  featureCounts \
    -a "$gtf" \
    -T "$THREADS" \
    -p \
    --countReadPairs \
    --largestOverlap \
    -o "$out" \
    "${BAMS[@]}"

  echo "Done."
} |& tee "$LOG"
